"""Async PostgreSQL connection pool using asyncpg.

The connection pool is created during FastAPI lifespan (`app/main.py`) and
shared across requests via ``get_db()``. The pool reference is held in this
module so any caller can ``async with get_db() as conn`` without threading the
pool through every dependency.

Schema is created on startup with ``init_db()``. Migrations are additive
(idempotent ``CREATE TABLE IF NOT EXISTS`` / ``ALTER TABLE ADD COLUMN IF NOT
EXISTS``) so re-running ``init_db()`` is safe.
"""

from __future__ import annotations

import contextlib
import logging
from collections.abc import AsyncIterator

import asyncpg

from app.config import settings

logger = logging.getLogger(__name__)

# Schema applied to fresh databases. Existing databases pick up additive
# changes via the idempotent guards in `_run_migrations`.
SCHEMA_SQL = """
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username CITEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS api_keys (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    key_hash TEXT NOT NULL UNIQUE,
    key_prefix TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL DEFAULT 'New Chat',
    system_prompt TEXT DEFAULT '',
    model_params TEXT
        DEFAULT '{"temperature":0.7,"max_tokens":4096,"top_p":0.9,"enable_thinking":false}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK(role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    reasoning TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    filename TEXT NOT NULL,
    file_hash TEXT NOT NULL,
    pages INTEGER,
    markdown_content TEXT NOT NULL,
    file_path TEXT,
    attachment_type TEXT NOT NULL DEFAULT 'pdf',
    mime_type TEXT,
    width INTEGER,
    height INTEGER,
    byte_size BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_conversations_updated_at ON conversations(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_user_updated_at
    ON conversations(user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_api_keys_user_id ON api_keys(user_id);
CREATE INDEX IF NOT EXISTS idx_attachments_conversation_id
    ON attachments(conversation_id);
CREATE INDEX IF NOT EXISTS idx_attachments_file_hash ON attachments(file_hash);
"""

# Module-level pool reference. Set by `create_pool()` (typically from
# FastAPI lifespan) and consumed by `get_db()`. Tests can also override via
# `set_pool()` so the same context-manager interface is used everywhere.
_pool: asyncpg.Pool | None = None


def get_pool() -> asyncpg.Pool:
    """Return the active connection pool, raising if not yet initialized."""
    if _pool is None:
        raise RuntimeError(
            "Database pool not initialized — call create_pool() at startup."
        )
    return _pool


def set_pool(pool: asyncpg.Pool | None) -> None:
    """Replace (or clear) the module-level pool. Used by tests."""
    global _pool
    _pool = pool


async def create_pool(dsn: str | None = None) -> asyncpg.Pool:
    """Create the asyncpg pool and store it module-level.

    Idempotent — calling twice returns the existing pool. Callers that want
    a fresh pool should `await close_pool()` first.
    """
    global _pool
    if _pool is not None:
        return _pool
    _pool = await asyncpg.create_pool(
        dsn=dsn or settings.database_url,
        min_size=settings.db_pool_min_size,
        max_size=settings.db_pool_max_size,
        command_timeout=settings.db_command_timeout,
    )
    return _pool


async def close_pool() -> None:
    """Close and clear the module-level pool."""
    global _pool
    if _pool is not None:
        await _pool.close()
        _pool = None


async def _run_migrations(conn: asyncpg.Connection) -> None:
    """Apply additive schema changes that aren't covered by SCHEMA_SQL alone.

    PG supports ``ADD COLUMN IF NOT EXISTS`` which makes additive migrations
    trivially idempotent — no need for ``information_schema.columns`` probes
    like the SQLite version had.
    """
    _ = await conn.execute(
        """
        ALTER TABLE attachments
            ADD COLUMN IF NOT EXISTS attachment_type TEXT NOT NULL DEFAULT 'pdf',
            ADD COLUMN IF NOT EXISTS mime_type TEXT,
            ADD COLUMN IF NOT EXISTS width INTEGER,
            ADD COLUMN IF NOT EXISTS height INTEGER,
            ADD COLUMN IF NOT EXISTS byte_size BIGINT
        """
    )


@contextlib.asynccontextmanager
async def get_db() -> AsyncIterator[asyncpg.Connection]:
    """Acquire a connection from the pool for the duration of the block.

    Usage::

        async with get_db() as conn:
            row = await conn.fetchrow("SELECT ... WHERE id = $1", id_)
    """
    pool = get_pool()
    async with pool.acquire() as conn:
        yield conn


async def init_db() -> None:
    """Create the schema and run additive migrations.

    Safe to call multiple times. Requires the pool to have been initialised
    via ``create_pool()`` first.
    """
    async with get_db() as conn:
        _ = await conn.execute(SCHEMA_SQL)
        await _run_migrations(conn)
    logger.info("Database initialized at %s", _redact_dsn(settings.database_url))


def _redact_dsn(dsn: str) -> str:
    """Return ``dsn`` with the password stripped, for logs."""
    # postgresql://user:password@host:port/db → postgresql://user:***@host:port/db
    import re

    return re.sub(r"(://[^:]+:)([^@]+)(@)", r"\1***\3", dsn)
